spring.application.name=college-planner-backend

spring.security.oauth2.client.registration.cognito.client-id=5cubhl46tc1fvvjbn1dftl6gh9
spring.security.oauth2.client.registration.cognito.client-secret=${COGNITO_CLIENT_SECRET}
gemini.api.key=${GEMINI_API_KEY}
spring.security.oauth2.client.registration.cognito.scope=openid,email,profile
spring.security.oauth2.client.registration.cognito.redirect-uri={baseUrl}/login/oauth2/code/cognito
spring.security.oauth2.client.registration.cognito.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.cognito.client-name=Cognito

spring.security.oauth2.client.provider.cognito.issuer-uri=https://cognito-idp.us-east-2.amazonaws.com/us-east-2_M1pZy3ddt

logging.level.org.springframework.security=DEBUG
